### ISSUE TITLE
Package with Lightning

### ISSUE THREAD

**Issue by balsama** [dawehner/content_translation_worfklow#2]
Thanks for this!

I assume you don't have plans to make this a full project. Do you have any issue with us pulling this into and packaging it with Lightning as a stopgap until we can migrate to content moderation?

Also, you mentioned that this can cause problems with the UI. Can you share any details about what/where?

**Comment by dawehner** [comment]
> I assume you don't have plans to make this a full project

I'd be happy to make this a real project. It just feels some really edgy usecase and hard for people to get. Shipping it as part of lightning would certainly helps as you would not think about it. Do you consider using this without the content_translation_revision module?

**Comment by balsama** [comment]
Background: we're getting issues in our queue about publishing forward revisions in Language A un-publishes Default rev in Language B. So yeah, we we thinking about bringing this in to _just_ fix that problem (without content_translation_revision). So it must not be _too_ much of an edge case :)

I was suggesting that we just dump this code into a sub-module of lightning_workflow. But if you were to make it a full project, we would just make it a dependency of lightning_workflow.

We would have to do some more testing to make sure it doesn't break any existing functionality - especially for users that don't use multilingual at all - which is why I was asking what UI problems this introduces.

Thanks again.

**Comment by dawehner** [comment]
> we're getting issues in our queue about publishing forward revisions in Language A un-publishes Default rev in Language B.

Yeah, this is exactly the problem we had when this module was created.

> We would have to do some more testing to make sure it doesn't break any existing functionality - especially for users that don't use multilingual at all

Oh yeah, I honestly also just use the module on one site yet, and the way how its implemented feel rather tricky, so please don't rush into that decision :)

> which is why I was asking what UI problems this introduces.

We IMHO fixes those UI problems (when you use content_translation_revision) by creating the automatic forward revision.

Feel free to ping me on IRC or whatever you like tomorrow to talk more about that.

**Comment by balsama** [comment]
pinging @phenaproxima

**Comment by phenaproxima** [comment]
@dawehner, I think what I'd prefer to do here is for you to promote this to a full project, which we would then bring into Lightning with a functional test of our own. Is that something you could do quickly?

**Comment by balsama** [comment]
Agree with @phenaproxima , but we should consider that if we bring the code into Lightning directly, we immediately get security team coverage too. Just another factor to consider. Esp if you're not comfortable tagging it right away.

**Comment by phenaproxima** [comment]
Speaking only for myself, I'm not terribly concerned about security coverage, because my feeling is that this should be promoted to a full project only for convenience (i.e., bringing it into Lightning and allowing other packages to use it as well as a stop-gap solution to this problem). If Workbench Moderation was still being actively maintained, it'd make more sense to have this as a patch for that. But since it's not, let's have it be a full project until Content Moderation is stable in core and Workbench Moderation dies off.

**Comment by balsama** [comment]
Promoted to a full project on D.O with an alpha tag by @dawehner, Thanks!

We ended up just documenting that this module can be used as a workaround.

**Comment by dawehner** [comment]
Note: i fixed some problems today, which makes it more reliable. I haven't
pushed a new tag
